#!/usr/bin/expect -f

set timeout 20

set f [open "/media/sageadmin/95B3-978B/Work/Dropbox/ResearchUMN/Unsorted/newpass.txt"]
set newhack [read $f]
close $f

set ip localhost

set user sageadmin

set password hexabun123

spawn su

expect "Password:"

send "$password\r"

expect "root*"

send " passwd sageadmin\r "

expect "Enter new UNIX password:"

send "$newhack\r"

expect "Retype new UNIX password:"

send "$newhack\r"

expect "root*"

send "exit\r";

interact
